#+TITLE: Computational Biology, Genomics and AI
#+SUBTITLE:  Strategic direction 2021-2026
#+AUTHOR: Timo La\ss mann, Feilman Fellow
#+OPTIONS: H:2 toc:nil
#+OPTIONS: tex:t
#+LATEX_CMD: pdflatex
#+LATEX_CLASS: simplepresentation
#+BEAMER_FRAME_LEVEL: 2


* Section 1
** Maths

Foo bar \(f(x) = \frac{x^3}{n}\) chicken checken.


Our best estimate of F(\nu) will be
\[
\hat{F}(\nu) = \frac{G(\nu)}{H(\nu)}.
\]


\begin{eqnarray*}
\hat{f}(x) & \propto & \sum_{\nu} \frac{|F(\nu)H(\nu)|^2}{|N(\nu)|^2}
           \frac{G(\nu)}{H(\nu)} e^{\frac{2 \pi i \nu x}{N}}\\
           & \propto & \sum_{\nu} \frac{|F(\nu)|^2}{|N(\nu)|^2} H(\nu) H^*(\nu)
           \frac{G(\nu)}{H(\nu)} e^{\frac{2 \pi i \nu x}{N}}\\
           & \propto & \sum_{\nu} H^*(\nu) G(\nu) e^{\frac{2 \pi i \nu x}{N}}
\end{eqnarray*}

\footref{styczynski-2008-blosum-miscal}


** Code

#+begin_src Lambda
Y := lambda g.(lambda x.g (x x)) (lambda x.g (x x))
#+end_src

#+begin_src C
  int main(int argc, char *argv[])
  {
          fprintf(stdout,"%d %d",one, two , three, ahgsdjhasgdagsdjhagsjagdjasgdjasgdjagsdjagdja);
          char tree = "tree";
          return 0;
  }
#+end_src

** List

1) sad a
2) adsa
   - dffff
   - ffff

***


** Quote test

*** adad                                                          :B_quote:
:PROPERTIES:
:BEAMER_env: quote
:END:
  Please please please pass on our deep gratitude and appreciation to the lovely Liz, Jonathan and all the
other beautiful, amazing staff at TKI who all ensured we had such a memorable, opulent weekend whilst having the opportunity to share our little girl's story and play a small part in enabling this vital research into undiagnosed diseases to continue.
Much love xix

#+BEGIN_SRC latex
  {\color{red} ffff}
  {\color{darkred} ffff}

#+END_SRC

#+BEGIN_SRC latex
{\color{foreground} ffff}
{\color{darkforeground} ffff}
#+END_SRC

*** New section                                              :B_definition:
:PROPERTIES:
:BEAMER_env: definition
:END:
$\Perm{n}{k}=\frac{n!}{(n-k)!}$ - permutation

$\binom nk=\Comb{n}{k}=\frac{n!}{k!(n-k)!}$ - combination


** First The quick brown fox jumpedn
- one
    Please please please pass on our deep gratitude and appreciation to the lovely Liz, Jonathan and all the
other beautiful, amazing staff at TKI who all ensured we had such a memorable, opulent weekend whilst having the opportunity to share our little girl's story and play a small part in enabling this vital research into undiagnosed diseases to continue.
Much love xix
- two

** Second
** Block test

*** TL                                                        :B_quotation:
:PROPERTIES:
:BEAMER_env: quotation
:END:
Red is blue


*** EXAMPLE                                                :B_exampleblock:
:PROPERTIES:
:BEAMER_env: exampleblock
:END:
GAGA
*** Normal Block                                                  :B_block:
:PROPERTIES:
:BEAMER_env: block
:END:

Normal block ...

*** Alert                                                    :B_alertblock:
:PROPERTIES:
:BEAMER_env: alertblock
:END:
Oh dear

** column test

*** Column                                                  :B_block:BMCOL:
:PROPERTIES:
:BEAMER_col: 0.45
:BEAMER_env: block
:END:

ASDA

*** 2nd:                                                    :B_block:BMCOL:
:PROPERTIES:
:BEAMER_col: 0.45
:BEAMER_env: block
:END:
FFFF
** Babel
   :PROPERTIES:
   :BEAMER_envargs: [t]
   :END:
*** COLOR???                                             :B_beamercolorbox:
:PROPERTIES:
:BEAMER_env: beamercolorbox
:END:


GAGA?


*** Octave code                 :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.45
    :BEAMER_env: block
    :END:
#+name: octaveexample
#+begin_example :results output :exports both
CAR
#+end_example

*** The output                  :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_col: 0.4
    :BEAMER_env: block
    :BEAMER_envargs: <2->
    :END:

#+results: octaveexample
#+begin_example
A =

   1   2
   3   4

x =

  -1
   1

#+end_example

** Table example

| asdasd | fasf af |
|--------+---------|
| asfa   | 45      |
|        |  43     |


*** Prooif                                                        :B_proof:
:PROPERTIES:
:BEAMER_env: proof
:END:
AFASFAD

*** Theory                                                      :B_theorem:
:PROPERTIES:
:BEAMER_env: theorem
:END:
asdasd

**                                                             :B_fullframe:
:PROPERTIES:
:BEAMER_env: fullframe
:END:


GAFASD A
*** adfsd a                                                      :B_column:
:PROPERTIES:
:BEAMER_env: column
:END:

column?> B_columnb
*** GGG                                                          :B_column:
:PROPERTIES:
:BEAMER_env: column
:END:
Another B_columnn


** New slide with refs

asdas supercite:abelson-1996-struc

supercite:weinstein-2020-gener-probab

supercite:trowbridge-1914

** References
\printbibliography

#+LATEX: \tiny \color{red}
#+BEGIN_SRC emacs-lisp :results output :exports results :eval yes
  (princ (concat (format "Emacs version:\n%s\n" (emacs-version))
                 (format "\norg version: %s\n" (org-version))))

#+END_SRC
